image: cboettig/labnotebook

script:
  - ls
  - pwd
  - git clone -b source https://github.com/cboettig/cboettig.github.io _source
  - cd _source && ls

#deploy:
#  bash:
#    script: 
#      - ./deploy.sh

